### ISSUE TITLE
USER STORY: add game

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#1]
As a **User** I can **add a game** so that **I can keep track of it**

# Tasks
- [ ] Create an HTML form to upload a new game
- [ ] Create User and game model
- [ ] Apply CRUD to model
