### ISSUE TITLE
USER STORY: Heroku deployment

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#13]
As a **developer** I can **access the project** so that **I can view and navigate the app on Heroku as I do on local**

# Tasks
- [x] Create env.py
- [x] Add database settingss
- [x] Add Profcile
- [x] Add port settings
- [x] Add Cloudinary settings

# Acceptance Criteria
- [x] App is visible on Heroku as it is on local
- [x] No broken link is present on Heroku
- [x] No broken image is present on Heroku 

# User Story score 1
