### ISSUE TITLE
USER STORY: Create Basic Model for Game 

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#14]
As an **admin** I can **create, read, update and delete Games** so that **I perform CRUD on Game instances**

# Tasks
- [x] Create Game Model
- [x] Add game fields to admin.py

# Acceptance Criteria
- [x] Games can be added to the admin panel
- [x] Games can be read in the admin panel
- [x] Games can be updated in the admin panel
- [x] Games can be deleted from the admin panel
- [x] Games can filtered 
- [x] All Game model field are visible and editable from the admin panel

# User Story Score 3
