### ISSUE TITLE
USER STORY: Add Platform model

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#15]
As a **Admin** I can **create, read, update, and delete platform instances** so that **I perform CRUD on platforms**

# Tasks
- [x] Create a model for the Platform
- [x] Add platform fields to admin.py

# Acceptance Criteria
- [x] Platforms can be added to the admin panel 
- [x] Platforms can be edited in the admin panel
- [x] Platforms can be read in the admin panel
- [x] Platforms can be deleted in the admin panel
- [x] Platforms can be filtered and sorted in the admin panel
- [x] All fields added in the Platform model are visible and editable in the admin panel 

# User Story score 3
