### ISSUE TITLE
USER STORY: View platform list

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#16]
As an **Admin** I can **See the list of platforms added outside the admin panel** so that **can verify the platform list view and home page perform as expected**

# Tasks
- [x] Create Platform detail view
- [x] Create homepage.html template
- [x] Add Bootstrap and Fontawesome settings

# Acceptance criteria
- [x] If a platform is added from the admin panel it must be visible in the admin panel

# User story score 5
