### ISSUE TITLE
USER STORY:  Game list view

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#17]
As an **Admin** I can **See the list of games added outside the admin panel** so that **can verify the game list view and html template perform as expected**

# Tasks
- [x] Add game list view
- [x] Edit the platform list template to show the list of games

# Acceptance Criteria
- [x]  All games added from the admin panel are visible on the template
- [x] Game Platform association is clear
