### ISSUE TITLE
USER STORY: Get in touch

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#18]
As a **Developer** I can **showcase who I am and my history** so that **I can empathize with the user**

# Tasks
- [x] Create about app
- [x] Create about model
- [x] Create about template
- [x] Create about view

# Acceptance Criteria
- [x] On the get in touch page I can have info on the developer
- [x] Users can access the get in touch page without login 

# User story score 3
