### ISSUE TITLE
USER STORY: Create login page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#19]
As a **User** I can **login into the app** so that **can see only my list of platforms and games**

# Tasks
- [x] Install Allauth
- [x] import Allauth template
- [x] edit Allauth template

# Acceptance Criteria 
- [x] User can log in
- [x] User can register
- [x] User can logout
- [x] Login, and register templates match with the app theme

# User Story score 2
