### ISSUE TITLE
USER STORY:  Create form to add Platforms

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#20]
As a **User** I can **add a platform to the app** so that  **I can keep track of the platforms I use**

# Tasks
- [ ] Create form.py
- [ ] Add post view to add platform instance
- [ ] Crete add platform.html template

# Acceptance Criteria 
- [ ] Platform can be added by the user 
- [ ] User can add platform name, category and image through the form

# User Story score 3
