### ISSUE TITLE
USER STORY: Add Game form

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#21]
As a **User** I can **add Games to a Platform** so that **I can keep track of the games played on each platform**

# Tasks
- [x] Create add Game post view
- [x] Create add game form in form.py
- [x] Add add game template

# Acceptance Criteria 
- [x] Users can add games using form templates 

# User Story score 2
