### ISSUE TITLE
USER STORY: Collaboration form

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#22]
As a **Developer** I can **get in touch with recruiters or other developers** so that **can receive offers to work on new projects or receive feedback**

# Tasks
- [ ] Add collaborate post view
- [ ] Add collaborate form in form.py
- [ ] Create a collaborative form template

# Acceptance Criteria 
- [ ] User can get in touch with the developer
- [ ] User can send a message to the developer

# User Story score 1
