### ISSUE TITLE
USER STORY: Edit platform

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#23]
As a **User** I can **edit the platform** so that **I can update the platform or correct mistakes added during creation**

# Tasks
- [x] Add view to edit platform
- [x] Add edit platform URL to url.py
- [x] Create an edit platform form and add it to form.py
- [x] Create edit  platform template

# Acceptance Criteria 
- [x] Edit all fields available during creation
- [x] Edit additional fields based on platform category
- [x] Edited fields and values should be visible on the platform detail

# User Story score 3
