### ISSUE TITLE
USER STORY: Delete Platform

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#24]
As a **User** I can **delete a platform instance** so that **I can remove platforms from the app**.

# Tasks
- [x] Add delete platform url
- [x] Create delete platform view
- [x] Create delete platform modal

# Acceptance Criteria 
- [x] User should be advised before deleting a platform
- [x] When a platform is deleted all related games should be deleted as well

# User Story score 5
