### ISSUE TITLE
USER STORY: Unit testing for Platform model

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#25]
As a **Developer** I can **test that a platform is created and its details are visible** so that **I can perform platform CRUD testing without manual intervention**.

# Tasks
- [x] Create a test for adding a Platform view
- [x] Create a test for the Platform detail view
- [x] Create a test for adding the platform form
- [x] Create a  test for creating a platform form

# Acceptance Criteria 
- [x] All run tests return no error

# User Story score 2
