### ISSUE TITLE
USER STORY: Unit test for get in touch app

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#26]
As a **Developer** I can **verify that the 'Get in Touch' content is displayed without manual testing** so that I can **save time during app testing**

# Tasks
- [ ] Creare a test for about view 
- [ ] Create a test for collaboration view
- [ ] Create a test for collaboration form

# Acceptance Criteria 
- [ ] all about model tests pass
- [ ] all collaboration model tests pass

# User Story score 3
