### ISSUE TITLE
USER STORY: Add image to Games

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#27]
As a **User** I can **add images to my games** so that **I can customize the game instances I add**.

# Tasks
- [x] Add image attribute to forms.py

# Acceptance Criteria 
- [x] Game image is visible on Platform details
- [x] Game image is visible when expanding each platform  

# User Story score 1
