### ISSUE TITLE
USER STORY: Game details 

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#28]
As a **User** I can **see game details** so that **I can get information and details on the games I have played**.

# Tasks
- [ ] Create game detail view
- [ ] Create a game detail template
- [ ] Create game detail URL

# Acceptance Criteria 
- [ ] Be able to see all game Metacritic and user score on game details
- [ ] Be able to see the game description on game details
- [ ] Be able to see the game image on game details

# User Story score 3
