### ISSUE TITLE
USER STORY: Game edit

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#29]
As a **User** I can **edit my game details** so that **I can customize my games instances**.

# Tasks
- [ ] Add edit game details url
- [ ] add edit game view
- [ ] add edit game form
- [ ] add game detail template

# Acceptance Criteria 
- [ ] I can edit all the game model attributes
- [ ] When game attributes are edited they are save on the game detail page

# User Story score 3
