### ISSUE TITLE
USER STORY: Delete Game

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#30]
As a **User** I can **delete a game instance** so that **I can remove unwanted games from my game list**.

# Tasks
- [ ] add remove game url.py
- [ ] add remove game view
- [ ] add remove game modal
- [ ] add remove game button

# Acceptance Criteria 
- [ ] Game can be removed from platform detail in the game list
- [ ] Game can be removed from Game details
- [ ] Once a Game is removed it does not appear any longer in the app

# User Story score 1
