### ISSUE TITLE
USER STORY: Wishlist model

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#31]
As an **Admin** I can **add wishlist instances** so that **I can manage and view wishlist items from the admin panel**.

# Tasks
- [ ] Review the wishlist model
- [ ] Add wishlist fields to admin.py

# Acceptance Criteria 
- [ ] Admin can add wishlist instances
- [ ] All wishlist fields can be edited in the admin panel
- [ ] wish list items can be filtered and sorted

# User Story score 1
