### ISSUE TITLE
USER STORY: Add wish list

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#32]
As a **User** I can **add wishlist items** so that **I can plan and keep track of the games I want to buy**.

# Tasks
- [x] Create a view to add wishlist items
- [x] Create a form to add wishlist items
- [x] Add a form to the HTML template

# Acceptance Criteria 
- [x] User can add wishlist items
- [x] wish list items are visible on the platform detail page
- [x] game name, price and store should be visible
- [x] wish list items should be listed in order of priority

# User Story score 3
