### ISSUE TITLE
USER STORY: Edit wish list

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#33]
As a **User** I can **edit a wishlist item** so that **I can update details such as price and priority**.

# Tasks
- [x] Create a view to edit the wishlist
- [x] Create URL for wish list edit
- [x] Create a wishlist detail HTML template

# Acceptance Criteria 
- [x] Wish list items can be edited by the user
- [x] Once fields are changed the updates are visible on the wishlist detail page 

# User Story score 2
