### ISSUE TITLE
USER STORY: Delete wish list

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#34]
As a **User** I can **delete wishlist items** so that **I can remove a game I no longer want to buy**.

# Tasks
- [x] Create a view to delete game
- [x] add javascript to delete game
- [x] Create an HTML modal to delete game

# Acceptance Criteria 
- [x] The user can delete the wishlist game by pushing the delete button
- [x] Once deleted the wishlist game no longer appears on the platform detail page

# User Story score 2
