### ISSUE TITLE
USER STORY: Presentation page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#35]
As a **User** I can **understand what the purpose of the app is** so that **I can decide if it fits my needs**.

# Tasks
- [ ] Create an HTML page
- [ ] Add the page as the first page visible to the user 
- [ ] Make sure the presentation page is visually appealing

# Acceptance Criteria 
- [ ] I can understand the purpose of the app by looking at the page
- [ ] The page is visually appealing

# User Story score 2
