### ISSUE TITLE
USER STORY: Instruction page

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#36]
As a **User ** I can  **understand how to use the app** so that **I can use it**

# Tasks
- [x] Create an HTML page including the instructions on how to use the app

# Acceptance Criteria 
- [x] By reading the page the user understands how to use the app
- [x] the page is accessible from the navbar 

# User Story score 1
