### ISSUE TITLE
USER STORY: Platform CRUD test

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#37]
As a **Developer** I can **test creating, reading, updating, and deleting Platform instances** so that **I can test Platform CRUD without manual input**.

# Tasks
- [x] Create a test for platform detail view
- [x] Create a test for add platform view
- [x] Create a test for delete platform view
- [x] Create a test for edit platform view

# Acceptance Criteria 
- [x] Platform CRUD can be tested without manual testing

# User Story score 2
