### ISSUE TITLE
USER STORY: Game CRUD Test

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#38]
As a **Developer** I can **test creating, reading, updating, and deleting Game instances** so that **I can test Game CRUD without manual input**

# Tasks
- [x] Create a test for game detail view
- [x]  Create a test for add game view
- [x] Create a test for delete game view
- [x]  Create a test for edit game view

# Acceptance Criteria 
- [x] Game CRUD can be tested without manual testing

# User Story score 1
