### ISSUE TITLE
USER STORY: Wish List Game CRUD test

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#39]
As a **Developer** I can **test creating, reading, updating and deleting WishListGames instances** so that **I can test WishListGame CRUD without manual input**.

# Tasks
- [x]  Create a test for wishlist_game detail view
- [x] Create a test for add wishlist_game view
- [x]  Create a test for delete wishlist_game view
- [x] Create a test for edit wishlist_game view

# Acceptance Criteria 
- [x]  WishList_Game CRUD can be tested without manual testing

# User Story score 1
