### ISSUE TITLE
USER STORY: Test form

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#40]
As a **Developer** I can **test forms' validity without manual input** so that **I can speed up and automate the app testing**.

# Tasks
- [x] Create Test for Add Game and Edit Game forms
- [x] Create a Test for Add Platform and Edit Platform forms
- [x] Create a Test for Add WishList Game form and Edit WishList Game forms

# Acceptance Criteria 
- [x] Forms for Add Game, Edut Game, Add Platform, Edit Platform, Add WishList Game Edit WishList Game can be tested with no manual input

# User Story score 1
