### ISSUE TITLE
USER STORY: Complete Documentation

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#41]
As a **User** I can **access all the details on the app's purpose, planning, and functions** so that **I can make an informed decision on whether it meets my needs**.

# Tasks
- [x] Review documentation added  so far
- [x] Add a section describing all app functionalities
- [x] Improve section describing project planning

# Acceptance Criteria 
- [x] It is clear how to use the app
- [x] App feature can be understood by reading documentation
- [x] Ideal user is described in detail

# User Story score 4
