### ISSUE TITLE
USER STORY: Coverage calculator

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#42]
As a **Developer** I can **analyze the test coverage percentage for views and forms** so that **I can prioritize manual testing efforts on uncovered areas**.
# Tasks
- [x] Install coverage library
- [x] run coverage library

# Acceptance Criteria 
- [x] Get coverage output
- [x]  Add what is not covered by unit testing in the documentation

# User Story score 1
