### ISSUE TITLE
USER STORY: Friend List

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#43]
As a **User** I can **add friends to the app** so that **I can share games, platforms and wishlists with them**.

# Tasks
- [ ] Create friend model
- [ ] Create CRUD for friend list
- [ ] Allow to black list users

# Acceptance Criteria 
- [ ] Friends can be added, viewed and deleted
- [ ] Friends can see games, platforms and wish list
- [ ] User can choose what to share with friends

# User Story score 5
