### ISSUE TITLE
USER STORY: IGDB API

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#44]
As a **User** I can **get Metacritic score, released date, developer and genres fields automatically filled** so that **I can speed up the adding game step**.

# Tasks
- [ ] Edit the game views so that the IGDB website is reached out to and the game name is passed to the IGDB API
- [ ] Verify IGDB  API is reached
- [ ] Take info from IGDB and use it to fill Game and Wish List game model

# Acceptance Criteria 
- [ ] User can add only the game name and Metacritic score, developer, genre and release date are updated automatically for the Game model
- [ ] User can add only game name and developer, genre and release date are updated automatically for the Wish List game model

# User Story score 4
