### ISSUE TITLE
USER STORY: Add link to store for Game in wish list

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#45]
As a **User** I can **seamlessly access the game store directly from the wishlist section of the app** so that **I can conveniently purchase desired games without switching between platforms**.

# Tasks
- [x] Add store link to wish list model
- [x] Add store link to wish list form

# Acceptance Criteria 
- [x] Store link is visible in the wish list section of the game

# User Story score 1
