### ISSUE TITLE
USER STORY: Create posts, clips and streams

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/The-Gamer-Library#46]
As a **User** I can **add posts, streams, and game clips** so that **I can share them with friends**.

# Tasks
- [ ] Create views to add game content
- [ ] Create templates for game content
- [ ] create forms for game content

# Acceptance Criteria 
- [ ] User posts are visible only by friends
- [ ] User can create, read, update and delete posts

# User Story score 5
